# GitLab CI for Terraform IaC
#
# This pipeline is used for cloud infrastructure deployments (AKS, EKS, etc.)
# Currently dormant - will be activated when experiments need cloud resources.
#
# To use: Create terraform config in experiments/<name>/terraform/ and update TF_ROOT below.
# See docs/adrs/ADR-001-gitlab-ci-for-iac.md for rationale.

stages:
  - validate
  - plan
  - apply

variables:
  # Update these when deploying cloud infrastructure for an experiment
  # TF_ROOT: experiments/<experiment-name>/terraform
  # TF_STATE_NAME: <experiment-name>
  TF_ROOT: ""
  TF_STATE_NAME: ""
  TF_HTTP_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${TF_STATE_NAME}
  TF_HTTP_LOCK_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${TF_STATE_NAME}/lock
  TF_HTTP_UNLOCK_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${TF_STATE_NAME}/lock
  TF_HTTP_USERNAME: gitlab-ci-token
  TF_HTTP_PASSWORD: ${CI_JOB_TOKEN}
  TF_HTTP_LOCK_METHOD: POST
  TF_HTTP_UNLOCK_METHOD: DELETE
  TF_HTTP_RETRY_WAIT_MIN: "5"

.terraform:
  image:
    name: hashicorp/terraform:1.9
    entrypoint: [""]
  before_script:
    - cd ${TF_ROOT}
    - terraform init
  rules:
    # Only run when TF_ROOT is configured
    - if: $TF_ROOT != ""

validate:
  extends: .terraform
  stage: validate
  script:
    - terraform validate

plan:
  extends: .terraform
  stage: plan
  script:
    - terraform plan -out=plan.tfplan
  artifacts:
    paths:
      - ${TF_ROOT}/plan.tfplan
      - ${TF_ROOT}/.terraform
      - ${TF_ROOT}/.terraform.lock.hcl
    expire_in: 1 week

apply:
  extends: .terraform
  stage: apply
  script:
    - terraform plan -out=plan.tfplan
    - terraform apply -auto-approve plan.tfplan
  rules:
    - if: $TF_ROOT != "" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
