---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: naive-db-nosync
  labels:
    app: naive-db-nosync
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: naive-db-nosync
  targetLabels:
    - app
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
