apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: locust
  namespace: locust
spec:
  hostnames:
  - locust.local
  parentRefs:
  - name: lab-gateway
    namespace: default
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: locust-master
      port: 8089
