---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: locust
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/illMadeCoder/illm-k8s-lab.git
    targetRevision: HEAD
    path: manifests/locust
  destination:
    server: https://kubernetes.default.svc
    namespace: locust
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
