# Bitnami Contour Helm Values
# https://github.com/bitnami/charts/tree/main/bitnami/contour

# Install Gateway API CRDs
installCRDs: true

# Contour configuration
contour:
  gatewayControllerName: projectcontour.io/gateway-controller
  manageCRDs: false

# Envoy configuration
envoy:
  service:
    type: LoadBalancer
