apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-labels.yaml
  - gateway.yaml
  - virtualservices.yaml
  - peer-authentication.yaml
  - destination-rules.yaml
  - tailscale-service.yaml
  - telemetry.yaml
