apiVersion: v1
kind: Service
metadata:
  name: cardinality-generator
  labels:
    app: cardinality-generator
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: cardinality-generator
---
apiVersion: v1
kind: Service
metadata:
  name: cardinality-generator-external
  labels:
    app: cardinality-generator
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: cardinality-generator
