apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cardinality-generator
  labels:
    app: cardinality-generator
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: cardinality-generator
  endpoints:
    - port: http
      interval: 15s
      path: /metrics
  namespaceSelector:
    matchNames:
      - tsdb-comparison
