apiVersion: v1
kind: Service
metadata:
  name: vm-hub
  namespace: observability
  annotations:
    tailscale.com/tailnet-fqdn: vm-hub.tailbdf608.ts.net
spec:
  ports:
    - name: http
      port: 8428
      targetPort: 8428
      protocol: TCP
  type: ExternalName
  externalName: placeholder
